# How to handle No Header Column Excel Dataset :-

In [2]:
import pandas as pd

In [3]:
data=pd.read_excel("C:\\Users\\rahul\\OneDrive\\Desktop\\DA Project\\dataset\\demo.xlsx")

In [4]:
data

  Unnamed: 0  Unnamed: 1
0        NaN         NaN
1       ravi        34.0
2       john        45.0
3      rahul        56.0
4     qwerty        56.0
5        abc        31.0
6        kbc        12.0

In [5]:
data.shape

(7, 2)

In [10]:
data=pd.read_excel("C:\\Users\\rahul\\OneDrive\\Desktop\\DA Project\\dataset\\demo.xlsx",header=None,skiprows=2,names=['Name','Age'])
data

     Name  Age
0    ravi   34
1    john   45
2   rahul   56
3  qwerty   56
4     abc   31
5     kbc   12

In [15]:
data.to_excel("C:/Users/rahul/OneDrive/Desktop/DA Project/dataset/New_demo.xlsx",index=False)